package statusboard.panels;

import java.awt.Color;
import javax.swing.JDialog;
import statusboard.Constants;
import statusboard.CrewMemberObject;
import statusboard.StatusBoard;
import static statusboard.StatusBoardFrame.backgroundColor;
import static statusboard.StatusBoardFrame.foregroundColor;
import statusboard.databaseHelpers.RosterDataBaseHelper;

public class AddEditMember extends javax.swing.JPanel {

    private static Constants con = new Constants();
    private static RosterDataBaseHelper db = RosterDataBaseHelper.getInstance();
    private final JDialog jdg;
    private CrewMemberObject crewMember = null;

    public AddEditMember(JDialog jdiag) {
        initComponents();
        jdg = jdiag;
        crewMember = null;
        setupColors();
    }

    public AddEditMember(JDialog jdiag, CrewMemberObject cmo) {
        jdg = jdiag;
        crewMember = cmo;
        initComponents();

        fNameText.setText(cmo.getFirstName());
        lNameText.setText(cmo.getLastName());
        deptComboBox.setSelectedItem(cmo.getDepartment());
        payGradeComboBox.setSelectedItem(cmo.getPayGrade());
        rankComboBox.setSelectedItem(cmo.getRank());
        barcodeText.setText(cmo.getBarcode());
        setupColors();
    }

    public void setBarcodeText(String barcode) {
        barcodeText.setText(barcode);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fNameLabel = new javax.swing.JLabel();
        fNameText = new javax.swing.JTextField();
        lNameLabel = new javax.swing.JLabel();
        lNameText = new javax.swing.JTextField();
        payGradeLabel = new javax.swing.JLabel();
        payGradeComboBox = new javax.swing.JComboBox<>();
        rankLabel = new javax.swing.JLabel();
        rankComboBox = new javax.swing.JComboBox<>();
        deptLabel = new javax.swing.JLabel();
        deptComboBox = new javax.swing.JComboBox<>();
        barcodeLabel = new javax.swing.JLabel();
        barcodeText = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        fNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fNameLabel.setText("First Name:");

        lNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lNameLabel.setText("Last Name:");

        lNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lNameTextActionPerformed(evt);
            }
        });

        payGradeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        payGradeLabel.setText("Pay Grade:");

        payGradeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(con.getPayGrades()));
        payGradeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payGradeComboBoxActionPerformed(evt);
            }
        });

        rankLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rankLabel.setText("Rank: ");

        deptLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        deptLabel.setText("Department:");

        deptComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(con.getDepartments()));

        barcodeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        barcodeLabel.setText("Barcode:");

        barcodeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barcodeTextActionPerformed(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(deptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(barcodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deptComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, 213, Short.MAX_VALUE)
                            .addComponent(barcodeText, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(payGradeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(rankLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(payGradeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rankComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lNameText)
                            .addComponent(fNameText)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(saveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelButton)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fNameLabel)
                    .addComponent(fNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(payGradeLabel)
                    .addComponent(payGradeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rankComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rankLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deptComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deptLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(barcodeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(barcodeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(cancelButton))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        jdg.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        // Don't save if Values are empty, colorize the labels red to indicate failure.
        boolean failure = false;
        if (fNameText.getText().equals("")) {
            fNameLabel.setForeground(Color.RED);
            failure = true;
        } else {
            fNameLabel.setForeground(Color.BLACK);
        }
        if (lNameText.getText().equals("")) {
            lNameLabel.setForeground(Color.RED);
            failure = true;
        } else {
            lNameLabel.setForeground(Color.BLACK);
        }
        if (payGradeComboBox.getSelectedItem().toString().equals("") || payGradeComboBox.getSelectedItem() == null) {
            payGradeLabel.setForeground(Color.RED);
            failure = true;
        } else {
            payGradeLabel.setForeground(Color.BLACK);
        }
        // add an extra check to this if/else block because the model may not have been set yet if the previous block fails.
        if (rankComboBox.getModel() == null || rankComboBox.getSelectedItem() == null || rankComboBox.getSelectedItem().toString().equals("")) {
            rankLabel.setForeground(Color.RED);
            failure = true;
        } else {
            rankLabel.setForeground(Color.BLACK);
        }
        if (deptComboBox.getSelectedItem().toString().equals("") || deptComboBox.getSelectedItem() == null) {
            deptLabel.setForeground(Color.RED);
            failure = true;
        } else {
            deptLabel.setForeground(Color.BLACK);
        }
        if (barcodeText.getText().equals("")) {
            barcodeLabel.setForeground(Color.RED);
            failure = true;
        } else {
            barcodeLabel.setForeground(Color.BLACK);
        }
        // break out if any of the above requirements fail.
        if (failure) {
            return;
        }

        if (crewMember == null) {
            db.insertRow(0, payGradeComboBox.getSelectedItem().toString(), rankComboBox.getSelectedItem().toString(), fNameText.getText(), lNameText.getText(), deptComboBox.getSelectedItem().toString(), barcodeText.getText(), Boolean.TRUE);
        } else {
            db.insertRow(crewMember.getId(), payGradeComboBox.getSelectedItem().toString(), rankComboBox.getSelectedItem().toString(), fNameText.getText(), lNameText.getText(), deptComboBox.getSelectedItem().toString(), barcodeText.getText(), Boolean.TRUE);
        }
        StatusBoard.sbf.refreshDeptTable(deptComboBox.getSelectedItem().toString());
        this.setVisible(false);
        jdg.dispose();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void barcodeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barcodeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barcodeTextActionPerformed

    private void payGradeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payGradeComboBoxActionPerformed
        // TODO add your handling code here:
        rankComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(con.getRanks(payGradeComboBox.getSelectedItem().toString())));
    }//GEN-LAST:event_payGradeComboBoxActionPerformed

    private void lNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lNameTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel barcodeLabel;
    private javax.swing.JTextField barcodeText;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox<String> deptComboBox;
    private javax.swing.JLabel deptLabel;
    private javax.swing.JLabel fNameLabel;
    private javax.swing.JTextField fNameText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lNameLabel;
    private javax.swing.JTextField lNameText;
    private javax.swing.JComboBox<String> payGradeComboBox;
    private javax.swing.JLabel payGradeLabel;
    private javax.swing.JComboBox<String> rankComboBox;
    private javax.swing.JLabel rankLabel;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables

    private void setupColors() {
        this.setBackground(backgroundColor);
        jdg.setBackground(backgroundColor);
        jdg.setForeground(foregroundColor);
        barcodeLabel.setBackground(backgroundColor);
        barcodeLabel.setForeground(foregroundColor);
        barcodeText.setBackground(backgroundColor);
        barcodeText.setForeground(foregroundColor);
        jPanel1.setBackground(backgroundColor);
        jPanel1.setForeground(foregroundColor);
        cancelButton.setBackground(backgroundColor);
        cancelButton.setForeground(foregroundColor);
        saveButton.setBackground(backgroundColor);
        saveButton.setForeground(foregroundColor);
        deptComboBox.setBackground(backgroundColor);
        deptComboBox.setForeground(foregroundColor);
        deptLabel.setBackground(backgroundColor);
        deptLabel.setForeground(foregroundColor);
        fNameLabel.setBackground(backgroundColor);
        fNameLabel.setForeground(foregroundColor);
        fNameText.setBackground(backgroundColor);
        fNameText.setForeground(foregroundColor);
        lNameLabel.setBackground(backgroundColor);
        lNameLabel.setForeground(foregroundColor);
        lNameText.setBackground(backgroundColor);
        lNameText.setForeground(foregroundColor);
        payGradeComboBox.setBackground(backgroundColor);
        payGradeComboBox.setForeground(foregroundColor);
        payGradeLabel.setBackground(backgroundColor);
        payGradeLabel.setForeground(foregroundColor);
        rankComboBox.setBackground(backgroundColor);
        rankComboBox.setForeground(foregroundColor);
        rankLabel.setBackground(backgroundColor);
        rankLabel.setForeground(foregroundColor);
    }

}
