package statusboard.panels;

import javax.swing.JDialog;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.TableColumn;
import statusboard.databaseHelpers.LoggingDataBaseHelper;
import statusboard.models.LogsListModel;

/**
 *
 * @author joe
 */
public class LogsList extends javax.swing.JPanel {
        private final JDialog jdg;
        private final LogsListModel logsListModel;
        private final JDialog aemDialog = new JDialog();
        private final LoggingDataBaseHelper db = LoggingDataBaseHelper.getInstance();


    /**
     * Creates new form UserList
     * @param jdiag
     */
    public LogsList(JDialog jdiag) {
        jdg = jdiag;
        logsListModel = new LogsListModel();
        initComponents();
        logsListTable.setAutoResizeMode(0);
        logsListTable.setOpaque(false);
        DefaultTableColumnModel colModel = (DefaultTableColumnModel) logsListTable.getColumnModel();

         TableColumn col;
         col = colModel.getColumn(0);
         col.setPreferredWidth(120);
         col.setWidth(120);

         col = colModel.getColumn(1);
         col.setPreferredWidth(100);
         col.setWidth(100);

         col = colModel.getColumn(2);
         col.setPreferredWidth(500);
         col.setWidth(500);

         jdg.pack();
         jdg.setLocationRelativeTo(null);
         jdg.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        logsListTable = new javax.swing.JTable();

        logsListTable.setModel(logsListModel);
        logsListTable.setColumnSelectionAllowed(true);
        logsListTable.setOpaque(false);
        logsListTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        logsListTable.setShowVerticalLines(false);
        logsListTable.setUpdateSelectionOnSort(false);
        jScrollPane1.setViewportView(logsListTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable logsListTable;
    // End of variables declaration//GEN-END:variables


}
